-- -- +goose Up
-- -- +goose StatementBegin
-- CREATE TABLE IF NOT EXISTS users (
--     id SERIAL PRIMARY KEY,
--     telegram_id INTEGER,
--     telegram_chat_id INTEGER
-- );
-- -- +goose StatementEnd

-- -- +goose Down
-- -- +goose StatementBegin
-- DROP TABLE users;
-- -- +goose StatementEnd
